### ISSUE TITLE
You guys should re-write it in Rust

### ISSUE THREAD

**Issue by mota** [LaKabane/libtuntap#12]
Targeting WebAssembly. It's 2018, bordel!

**Comment by Aversiste** [comment]
A Rust wrapper is something interesting to consider but the next trend sure will be [Zig](https://ziglang.org/) where nothing needs to be done, foutrediable !

**Comment by mota** [comment]
I'm sorry to re-open but I.LOVE.ZIG! Crevindiou!

**Comment by Aversiste** [comment]
Yes it is very promising. I am not successful yet at compiling it under OpenBSD but I will keep trying every now and then.
