### ISSUE TITLE
Java bindings?

### ISSUE THREAD

**Issue by profitware** [LaKabane/libtuntap#14]
Hi, @Aversiste !

Are there any plans on creating Java bindings for libtuntap? I would like to use the library in my research project on creating dummy overlay network using Clojure (https://github.com/yaosdn). Since there's no Java bindings I've been using [JavaLinuxNet](https://github.com/lucwillems/JavaLinuxNet) ([clj-linux-net](https://github.com/yaosdn/clj-linux-net) wrapper) for tuntap functionality, but it is not portable to platforms other than Linux.

I don't mind creating one if there are no such plans, but I've got no experience neither in C/C++ nor in Java/JNI, so I don't know how long would it take.

Thank you.

**Comment by Aversiste** [comment]
Hello,

There is no plan for Java binding currently as I am not a Java developer, and neither is @chipot. However if you want to create one yourself you would have my support :)

Regards.
