### ISSUE TITLE
make on windows error

### ISSUE THREAD

**Issue by Mikhail29** [LaKabane/libtuntap#21]
I have some problem. When I execute the command "make" it displays

> In file included from E:/users/mixajlov.mikhail/Documents/libtuntap/bindings/cpp/tuntap++.hh:7,
>                  from E:/users/mixajlov.mikhail/Documents/libtuntap/bindings/cpp/tuntap++.cc:1:
> E:/users/mixajlov.mikhail/Documents/libtuntap/tuntap.h:60:9: error: 'HANDLE' does not name a type
>  typedef HANDLE t_tun;
>          ^~~~~~
> E:/users/mixajlov.mikhail/Documents/libtuntap/tuntap.h:90:15: error: 't_tun' does not name a type
>  TUNTAP_EXPORT t_tun   tuntap_get_fd(struct device *);
>                ^~~~~
> E:/users/mixajlov.mikhail/Documents/libtuntap/bindings/cpp/tuntap++.cc: In member function 'tuntap::tun tuntap::tun::native_handle() const':
> E:/users/mixajlov.mikhail/Documents/libtuntap/bindings/cpp/tuntap++.cc:46:12: error: 'tuntap_get_fd' was not declared in this scope
>      return tuntap_get_fd(this->_dev);
>             ^~~~~~~~~~~~~
> E:/users/mixajlov.mikhail/Documents/libtuntap/bindings/cpp/tuntap++.cc:46:12: note: suggested alternative: 'tuntap_set_ip'
>      return tuntap_get_fd(this->_dev);
>             ^~~~~~~~~~~~~
>             tuntap_set_ip
> E:/users/mixajlov.mikhail/Documents/libtuntap/bindings/cpp/tuntap++.cc: In member function 'tuntap::tun tuntap::tap::native_handle() const':
> E:/users/mixajlov.mikhail/Documents/libtuntap/bindings/cpp/tuntap++.cc:136:12: error: 'tuntap_get_fd' was not declared in this scope
>      return tuntap_get_fd(this->_dev);
>             ^~~~~~~~~~~~~
> E:/users/mixajlov.mikhail/Documents/libtuntap/bindings/cpp/tuntap++.cc:136:12: note: suggested alternative: 'tuntap_set_ip'
>      return tuntap_get_fd(this->_dev);
>             ^~~~~~~~~~~~~
>             tuntap_set_ip
> make[2]: *** [bindings/cpp/CMakeFiles/tuntap++.dir/tuntap++.cc.obj] Ошибка 1
> make[1]: *** [bindings/cpp/CMakeFiles/tuntap++.dir/all] Ошибка 2
> make: *** [all] Ошибка 2

How can i fix it?

**Comment by gambarUCLV** [comment]
you may need change tuntap.h header file and add to it windows.h header in windows section
[tuntap.zip](https://github.com/LaKabane/libtuntap/files/4120453/tuntap.zip)

**Comment by Aversiste** [comment]
Hello,

It should be fixed with commit 2362f545b0e56e053dab473ea6038e05895872d5, can you give it a try?

Regards.
