### ISSUE TITLE
t_tuntap_log causing linking failure

### ISSUE THREAD

**Issue by Polpetta** [LaKabane/libtuntap#3]
Hello. When using this library (with C++) I get an error by the linker stating that `t_tuntap_log` is defined multiple times in `tuntap.h` line 146. It seems that the problematic line is this:
https://github.com/LaKabane/libtuntap/blob/b7e25a42b35023e39d69cd104e9f50b2cb237d5a/tuntap.h#L146

Removing that, after the lib installation, makes everything work, but if it's removed before the library compilation you get the following error:
```
[dpolonio@davmark build]$ make 
Scanning dependencies of target tuntap-static
[ 10%] Building C object CMakeFiles/tuntap-static.dir/tuntap.c.o
/home/dpolonio/Desktop/Repo/libtuntap/tuntap.c: In function ‘tuntap_init’:
/home/dpolonio/Desktop/Repo/libtuntap/tuntap.c:48:2: error: ‘tuntap_log’ undeclared (first use in this function); did you mean ‘t_tuntap_log’?
  tuntap_log = tuntap_log_default;
  ^~~~~~~~~~
  t_tuntap_log
/home/dpolonio/Desktop/Repo/libtuntap/tuntap.c:48:2: note: each undeclared identifier is reported only once for each function it appears in
/home/dpolonio/Desktop/Repo/libtuntap/tuntap.c: In function ‘tuntap_set_ip’:
/home/dpolonio/Desktop/Repo/libtuntap/tuntap.c:77:3: warning: implicit declaration of function ‘tuntap_log’; did you mean ‘tuntap_down’? [-Wimplicit-function-declaration]
   tuntap_log(TUNTAP_LOG_NOTICE, "Device is not started");
   ^~~~~~~~~~
   tuntap_down
make[2]: *** [CMakeFiles/tuntap-static.dir/build.make:63: CMakeFiles/tuntap-static.dir/tuntap.c.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:73: CMakeFiles/tuntap-static.dir/all] Error 2
make: *** [Makefile:130: all] Error 2
```

**Comment by Aversiste** [comment]
Hello, and thanks for the report.

Can you tell me which compiler and OS are you using ? Also, are you trying to build the C++ wrapper tuntap++ ?

We are exporting `tuntap_log` but I am not sure it is necessary, this symbol is an internal function pointer.

Regards.

**Comment by Aversiste** [comment]
I tested the minimal example you provided without problems with the following C++ compliers:

* clang (OpenBSD clang version 6.0.0) ;
* eg++ (4.9.4)
* g++ (4.2.1)

Anyway I pushed a few commits on branch `issue-3`, can you test them ? They basically hid the wrongdoing symbol.

**Comment by Aversiste** [comment]
FYI: this g++ is provided from the base OpenBSD system while eg++ is the “external” one from the packages.

**Comment by Polpetta** [comment]
Hey, we've tried the branch and it works like a charm! We made a PR adding the `tuntap++` module in the `make install` command when `ENABLE_CXX` flag is activated.

Thanks for your time, cheers!

**Comment by Aversiste** [comment]
I am slowly getting back on this project so don't hesitate to suggest enhancements and ask about missing features.

**Comment by Polpetta** [comment]
Nice! Sure, if we came up with other enhancements for this library we'll open a pr/issue! :+1:

**Comment by CapacitorSet** [comment]
Likewise for the current version, I'm getting multiple definitions of `tuntap_log`:

```
/usr/bin/ld: ../lib/libtuntap.a(tuntap_log.c.o):(.bss+0x0): multiple definition of `tuntap_log'; ../lib/libtuntap.a(tuntap.c.o):(.bss+0x0): first defined here
/usr/bin/ld: ../lib/libtuntap.a(tuntap-unix.c.o):(.bss+0x0): multiple definition of `tuntap_log'; ../lib/libtuntap.a(tuntap.c.o):(.bss+0x0): first defined here
/usr/bin/ld: ../lib/libtuntap.a(tuntap-unix-linux.c.o):(.bss+0x0): multiple definition of `tuntap_log'; ../lib/libtuntap.a(tuntap.c.o):(.bss+0x0): first defined here
```

Simply declaring it static fixes that, though:

```diff
diff --git a/private.h b/private.h
index 743b228..2e38255 100644
--- a/private.h
+++ b/private.h
@@ -105,7 +105,7 @@ struct device {
 # endif
 
 /* Internal log facilities */
-t_tuntap_log tuntap_log;
+static t_tuntap_log tuntap_log;
 void    tuntap_log_default(int, const char *);
 void    tuntap_log_hexdump(void *, size_t);
 void    tuntap_log_chksum(void *, int);
```
