### ISSUE TITLE
Confegrating libtuntap and Tunnelblick  

### ISSUE THREAD

**Issue by ArenAlyahya** [LaKabane/libtuntap#37]
Hi,
I am working on an overly network research, and I wonder if I could use libtuntap on a Linux server and Tunnelblick on client macOS Big Sur. I want to redirect specific traffic on macOS to be directed to Linux through the tun tunnel.

**Comment by tleguern** [comment]
Hello,

macOS Big Sur was released after High Sierra and is thus not supported by libtuntap.
It will remain the case as long as issue #31 is not fixed.
