### ISSUE TITLE
Error in running test01 in windows

### ISSUE THREAD

**Issue by fengyc** [LaKabane/libtuntap#38]
OS: win11
Tuntap driver:  latest openvpn, should be https://github.com/OpenVPN/tap-windows6 ， release date 2020/10/8 , version 9.24.6.601

When I debug the test01 in visualstudio2019 ( UAC requireAdministrator (/level='requireAdministrator') )，I found that the `tuntap_start - CreateFile` function return an error TUNFD_INVALID_VALUE , and then it shows an error message like `file not found`.

Is the libtuntap compatible with the driver ?

**Comment by tleguern** [comment]
Not tested, sorry. I have been on OpenBSD and Linux for years now.
