### ISSUE TITLE
Question: Includeing libtuntap with pkg-config

### ISSUE THREAD

**Issue by marek22k** [LaKabane/libtuntap#47]
Hello,

I would like to use libtuntap in my program. I use Meson, which in turn uses cmake and pkg-config to search for libraries. I have now built and installed libtuntap:
```
$ file /usr/include/tuntap++.hh
/usr/include/tuntap++.hh: C++ source, ASCII text
$ file /usr/include/tuntap++.hh
/usr/include/tuntap++.hh: C++ source, ASCII text
$ file /usr/include/tuntap.h
/usr/include/tuntap.h: C source, ASCII text
$ file /usr/lib/libtuntap++.a
/usr/lib/libtuntap++.a: current ar archive
$ file /usr/lib/libtuntap.a
/usr/lib/libtuntap.a: current ar archive
```
But when I try to find the library with pkg-config, it doesn't work. `pkg-config --list-all | grep tuntap` returns nothing.

Is there a mistake on my part? Is there a way to use the library with pkg-config?

I hope it's ok if I ask here.

**Comment by marek22k** [comment]
Workaround / Alternative when using meson: https://github.com/mesonbuild/meson/issues/7281#issuecomment-932887170

**Comment by eli-schwartz** [comment]
It would still be best to actually provide a pkg-config file. Using find_library is a hack to work around the lack of one, but it is not as flexible.
